INSERT INTO TB_PERFIL(DESCRICAO, AUTORIEDADE) VALUES ('Administrador', 'ROLE_ADMIN');
INSERT INTO TB_PERFIL(DESCRICAO, AUTORIEDADE) VALUES ('Cliente', 'ROLE_CLIENTE');

INSERT INTO TB_USUARIO(NOME, SOBRENOME, EMAIL, DATA_CADASTRO, DATA_ATUALIZACAO) VALUES ('José', 'Silva', 'jose@email.com', NOW(), NULL);
INSERT INTO TB_USUARIO_PERFIL(ID_USUARIO, ID_PERFIL) VALUES (1, 1);
INSERT INTO TB_USUARIO_PERFIL(ID_USUARIO, ID_PERFIL) VALUES (1, 2);