spring:
  datasource:
    url: jdbc:mysql://localhost:3307/contrato_dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
logging:
  level:
    org:
      flywaydb: DEBUG

pagamento:
  online:
    servico: PayPalService